------------------------------------------------------------------------------------
-- SCRIPT
------------------------------------------------------------------------------------


-- CRIANDO BANCO DE DADOS
------------------------------------------------------------------------------------
CREATE DATABASE TREINAMENTO;
GO

USE TREINAMENTO;
GO


-- CRIANDO TABELA DEPARTAMENTO
------------------------------------------------------------------------------------
CREATE TABLE DEPARTAMENTO
(    
    ID varchar(40) NOT NULL,                     -- Identificador único do registro.    
    CODIGO numeric(6) NOT NULL,                  -- Código do departamento.
    DESCRICAO varchar(100) NOT NULL              -- Descrição do departamento.
)
GO

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT PK_DEPARTAMENTO
    PRIMARY KEY CLUSTERED (ID)
GO

CREATE UNIQUE INDEX IDX_DEPARTAMENTO
ON DEPARTAMENTO (CODIGO ASC)
GO

-- CRIANDO TABELA FUNCIONARIO
------------------------------------------------------------------------------------
CREATE TABLE FUNCIONARIO
(    
    ID varchar(40) NOT NULL,             -- Identificador único do registro.    
    CODIGO numeric(6) NOT NULL,          -- Código do funcionário.
    NOME varchar(100) NOT NULL,          -- Nome do funcionário.
    IDDEPARTAMENTO varchar(40) NOT NULL  -- Identificador do departamento
)
GO

ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO
    PRIMARY KEY CLUSTERED (ID)
GO

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO
    FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO (ID)
GO

CREATE UNIQUE INDEX IDX_FUNCIONARIO
ON FUNCIONARIO (CODIGO ASC)
GO


-- INSERINDO DADOS NAS TABELAS
------------------------------------------------------------------------------------
DECLARE @IDDESENVOLVIMENTO VARCHAR(40) = NEWID();
DECLARE @IDSUPORTE VARCHAR(40) = NEWID();
DECLARE @IDTI VARCHAR(40) = NEWID();
DECLARE @IDRH VARCHAR(40) = NEWID();

INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (@IDDESENVOLVIMENTO, 1, 'DESENVOLVIMENTO');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (@IDSUPORTE, 2, 'SUPORTE');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (@IDTI, 3, 'TI');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (@IDRH, 4, 'RH');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 5, 'FINANCEIRO');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 6, 'COMERCIAL');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 7, 'IMPLANTACAO');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 8, 'PLANEJAMENTO');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 9, 'CONTABILIDADE');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 10, 'ADMINISTRACAO');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 11, 'DIRETORIA');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 12, 'RECEPCAO');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 13, 'COMUNICACAO');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 14, 'TECNOLOGIAS');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 15, 'PRODUTOS');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 16, 'RECRUTAMENTO');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 17, 'ACADEMIA');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 18, 'COMPETENCIAS');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 19, 'LMS');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 20, 'MOBILE');
INSERT INTO DEPARTAMENTO (ID, CODIGO, DESCRICAO) VALUES (NEWID(), 21, 'REPORTS');

INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 1, 'JOAO', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 2, 'MARIA', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 3, 'PEDRO', @IDSUPORTE);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 4, 'ALINE', @IDSUPORTE);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 5, 'JOYCE', @IDTI);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 6, 'FLAVIA', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 7, 'ANA', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 8, 'ALICE', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 9, 'BEATRIZ', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 10, 'MARCOS', @IDSUPORTE);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 11, 'MAGNO', @IDSUPORTE);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 12, 'CLEBER', @IDTI);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 13, 'LEANDRO', @IDTI);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 14, 'BRUNA', @IDTI);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 15, 'JULIO', @IDTI);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 16, 'ALESSANDRO', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 17, 'TIAGO', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 18, 'RICARDO', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 19, 'FABRICIO', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 20, 'CAIO', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 21, 'KARLA', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 22, 'PRISCILA', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 23, 'DANILO', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 24, 'JAQUELINE', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 25, 'FLAVIANE', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 26, 'HENRIQUE', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 27, 'JEFFERSON', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 28, 'DIEGO', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 29, 'ANGELICA', @IDRH);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 30, 'DEBORA', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 31, 'VINICIUS', @IDDESENVOLVIMENTO);
INSERT INTO FUNCIONARIO (ID, CODIGO, NOME, IDDEPARTAMENTO) VALUES (NEWID(), 32, 'LUKE', @IDDESENVOLVIMENTO);